import type { ContentEntry } from "../types";

export const blogs: ContentEntry[] = [
  {
    kind: "blog",
    slug: "why-intelligent-people-freeze-under-pressure",
    title: "Why Intelligent People Freeze Under Pressure",
    excerpt: "Freezing is not a lack of intelligence. It is what happens when cognitive load, identity threat, and real-time judgment collide.",
    category: "Pressure Psychology",
    author: "RehearseAI Research",
    readTime: "9 min read",
    publishedAt: "2026-05-01",
    heroImage: "cognitive-freeze",
    tags: ["pressure", "confidence", "reasoning"],
    content: [
      { type: "paragraph", text: "A strange thing happens to smart people in high-stakes rooms. They know the answer. They have thought about the issue before. They may even have explained it beautifully in private. Then the interviewer leans forward, a panelist interrupts, or a manager asks for a sharper example, and the mind goes quiet. The person is not suddenly less intelligent. They are overloaded." },
      { type: "paragraph", text: "Freezing under pressure is often misread as weakness. In reality, it is usually a coordination failure between memory, emotion, self-monitoring, and real-time language. Your brain is trying to retrieve facts, predict judgment, manage your image, choose words, and stay socially safe at the same time. That is a lot of traffic for one narrow bridge." },
      { type: "heading", text: "The problem is not knowledge. It is access." },
      { type: "paragraph", text: "Under calm conditions, intelligent people can explore nuance. They can compare options, refine a claim, and find the cleanest explanation. Under pressure, the brain prioritizes threat detection. It asks: Am I safe? Am I being judged? Did I just sound stupid? What will they think next? Those questions consume bandwidth before the real answer even starts forming." },
      { type: "quote", text: "Pressure does not erase intelligence. It interrupts access to it." },
      { type: "paragraph", text: "This is why people often think of the perfect answer ten minutes after the meeting ends. The information was there. The pressure state made it hard to reach. When the body relaxes, the mind reopens its search space." },
      { type: "heading", text: "Identity threat makes freezing worse" },
      { type: "paragraph", text: "The more you care about being seen as competent, the easier it is to freeze. A junior person may freeze because they fear exposure. A senior person may freeze because they fear losing status. A founder may freeze because their idea feels personal. A researcher may freeze because the question touches years of work. The stakes are not only about the answer. They are about what the answer seems to reveal about you." },
      { type: "paragraph", text: "That emotional layer changes speech. You hedge more. You over-explain. You rush. You defend before clarifying. Sometimes you abandon structure and start searching out loud, hoping the answer will appear mid-sentence. Listeners experience that as uncertainty, even when the underlying thinking is good." },
      { type: "heading", text: "The way out is rehearsal under realistic friction" },
      { type: "paragraph", text: "Reading advice is useful, but pressure has to be practiced in the same channel where it appears: live response. You need to experience follow-up questions, interruptions, skeptical faces, and the feeling of not having unlimited time. Then you need feedback on the pattern, not just the content." },
      { type: "insight", title: "Practice target", text: "Train retrieval under pressure. Give concise answers, then add evidence. Do not wait for the perfect sentence before beginning." },
      { type: "paragraph", text: "RehearseAI is built for this exact gap. It does not treat conversation as a casual chat. It creates pressure, watches how your reasoning changes, and helps you recover access to the intelligence you already have before the real room tests it." },
    ],
  },
  {
    kind: "blog",
    slug: "hidden-psychology-of-interview-anxiety",
    title: "The Hidden Psychology of Interview Anxiety",
    excerpt: "Interview anxiety is not only fear of rejection. It is a live collision between identity, uncertainty, and compressed performance.",
    category: "Interview Intelligence",
    author: "RehearseAI Research",
    readTime: "10 min read",
    publishedAt: "2026-05-03",
    heroImage: "interview-anxiety",
    tags: ["interviews", "anxiety", "preparation"],
    content: [
      { type: "paragraph", text: "Interview anxiety often feels embarrassing because the situation looks simple from the outside. Someone asks questions. You answer them. Yet inside, the experience can feel like a spotlight attached to your nervous system. Every pause feels too long. Every vague phrase feels fatal. Every follow-up sounds like a verdict." },
      { type: "paragraph", text: "The hidden psychology is that interviews are not just information exchanges. They are status evaluations. You are trying to communicate capability while being measured by people who may control access to money, identity, opportunity, and belonging. The body notices that before the mind can rationalize it away." },
      { type: "heading", text: "An interview compresses your whole story" },
      { type: "paragraph", text: "Most people are anxious because they are trying to compress years of effort into minutes of speech. You are not only answering, 'Tell me about yourself.' You are trying to prove that your path makes sense, your choices were intelligent, your failures taught you something, and your future is worth betting on. That is a heavy cognitive task." },
      { type: "paragraph", text: "Anxiety rises when the story is not yet organized. If your examples are scattered, your brain has to search while speaking. That creates pauses, filler words, and rambling. The solution is not memorizing a script. It is building a flexible map: claim, evidence, lesson, relevance." },
      { type: "quote", text: "The best candidates do not sound rehearsed. They sound organized under uncertainty." },
      { type: "heading", text: "The fear beneath the fear" },
      { type: "paragraph", text: "Many candidates think they fear hard questions. More often, they fear what a hard question might imply: maybe I am not ready, maybe I do not belong, maybe they will see through me. That inner narrative changes the outer answer. Instead of clarifying the question, the candidate defends. Instead of giving evidence, they reassure. Instead of pausing, they rush." },
      { type: "paragraph", text: "This is why realistic practice matters. You need to learn that a skeptical follow-up is not an attack. It is an invitation to show structure. When the interviewer says, 'Can you be more specific?' the strong move is not panic. It is precision." },
      { type: "heading", text: "Anxiety falls when the room becomes familiar" },
      { type: "paragraph", text: "Repetition changes the emotional meaning of the interview. The first time you face a skeptical question, it feels personal. The tenth time, it feels like a known pattern. You start recognizing question types: evidence request, prioritization test, conflict probe, ambiguity challenge, motivation check. Familiarity creates calm." },
      { type: "insight", title: "Interview reset", text: "When anxiety spikes, slow the first sentence. A calm opening gives your brain time to organize the rest." },
      { type: "paragraph", text: "RehearseAI helps candidates practice that familiarity. It simulates realistic pressure, tracks where anxiety changes your reasoning, and turns interviews into trainable performance rather than mysterious judgment." },
    ],
  },
  {
    kind: "blog",
    slug: "how-pressure-changes-the-way-you-think",
    title: "How Pressure Changes the Way You Think",
    excerpt: "Pressure narrows attention, shortens reasoning, and makes familiar ideas harder to express. Here is how to train against it.",
    category: "Cognitive Performance",
    author: "RehearseAI Research",
    readTime: "8 min read",
    publishedAt: "2026-05-05",
    heroImage: "pressure-thinking",
    tags: ["pressure", "thinking", "performance"],
    content: [
      { type: "paragraph", text: "Pressure is not just a feeling. It is a cognitive filter. When stakes rise, attention narrows. The mind becomes more selective, faster, and more defensive. That can help in emergencies, but it can hurt in conversations that require nuance, structure, and persuasion." },
      { type: "heading", text: "Pressure reduces your working space" },
      { type: "paragraph", text: "Working memory is the mental surface where you hold a question, compare possible answers, and choose language. Under pressure, that surface shrinks. You may remember the first part of the question and lose the second. You may make a claim and forget to support it. You may hear a challenge as disagreement rather than curiosity." },
      { type: "paragraph", text: "This explains why high-pressure answers often become shorter in the wrong places and longer in the wrong places. People skip the central logic, then overcompensate with extra detail." },
      { type: "quote", text: "Pressure does not only change what you feel. It changes what information your mind can hold." },
      { type: "heading", text: "Pressure favors familiar patterns" },
      { type: "paragraph", text: "When the brain is overloaded, it reaches for familiar scripts. That is why people repeat phrases like 'I am passionate,' 'I work well under pressure,' or 'communication is important.' These phrases are not wrong, but they are often too generic. Pressure makes them easier to reach than specific evidence." },
      { type: "paragraph", text: "Training means building better defaults. Instead of memorizing perfect paragraphs, you practice structures that hold under pressure: answer first, evidence second, tradeoff third. Or situation, action, result, reflection. Or claim, reason, example, implication." },
      { type: "heading", text: "Pressure can be useful when trained" },
      { type: "paragraph", text: "Not all pressure is bad. A moderate level can sharpen attention and bring energy to your voice. The goal is not to eliminate pressure. The goal is to stop pressure from taking control of your reasoning. You want enough activation to be present, not so much that you lose structure." },
      { type: "insight", title: "Training move", text: "Practice with escalating difficulty. Start friendly, then realistic, then skeptical. Let your nervous system learn the pattern." },
      { type: "paragraph", text: "RehearseAI is designed around this principle. It lets pressure become measurable, repeatable, and coachable, so your thinking stays available when the real room gets hard." },
    ],
  },
  {
    kind: "blog",
    slug: "why-most-people-sound-less-intelligent-in-live-conversations",
    title: "Why Most People Sound Less Intelligent in Live Conversations",
    excerpt: "Live conversation taxes clarity differently than writing or private thinking. Intelligence has to be translated in real time.",
    category: "Communication Psychology",
    author: "RehearseAI Research",
    readTime: "9 min read",
    publishedAt: "2026-05-07",
    heroImage: "live-conversation",
    tags: ["conversation", "clarity", "communication"],
    content: [
      { type: "paragraph", text: "Many thoughtful people are better thinkers than speakers. Their written ideas are sharp, but live conversation makes them sound vague, hesitant, or scattered. This gap can feel unfair. It is also trainable." },
      { type: "heading", text: "Speaking is thinking with a timer" },
      { type: "paragraph", text: "Writing lets you revise. Conversation does not. In live speech, you have to understand the question, choose the frame, manage emotion, monitor the listener, and produce language in sequence. That sequence creates risk. If the first sentence is weak, the rest of the answer has to recover while still moving forward." },
      { type: "paragraph", text: "The most common problem is starting too far from the point. People begin with background, disclaimers, or context because they are still finding the answer. The listener hears uncertainty. A stronger move is to give the headline first, then earn nuance." },
      { type: "quote", text: "Live intelligence is not just what you know. It is how quickly you can structure what you know for another mind." },
      { type: "heading", text: "The listener cannot see your internal complexity" },
      { type: "paragraph", text: "Inside your head, the answer may be rich. Outside, the listener only receives the words in order. If the structure is hidden, intelligence is hidden. This is why people with deep knowledge sometimes lose to people with cleaner framing." },
      { type: "paragraph", text: "Good live communication creates handles for the listener: 'There are three reasons,' 'The tradeoff is,' 'The risk is,' 'My recommendation is.' These phrases are not corporate filler. They are cognitive signposts." },
      { type: "heading", text: "Practice should train translation" },
      { type: "paragraph", text: "The skill is translating messy thought into usable speech. That requires repetition with feedback. Did you answer the question? Did you support the claim? Did your structure survive a follow-up? Did you recover after interruption?" },
      { type: "insight", title: "Live clarity rule", text: "If your answer has no first sentence, it has no structure. Start with the point." },
      { type: "paragraph", text: "RehearseAI helps close the gap between private intelligence and live expression by creating realistic conversational pressure and showing how your thinking lands in real time." },
    ],
  },
  {
    kind: "blog",
    slug: "science-of-calmness-during-difficult-conversations",
    title: "The Science of Calmness During Difficult Conversations",
    excerpt: "Calmness is not passivity. It is the ability to keep your reasoning online while emotion enters the room.",
    category: "Difficult Conversations",
    author: "RehearseAI Research",
    readTime: "8 min read",
    publishedAt: "2026-05-09",
    heroImage: "calmness",
    tags: ["calmness", "conflict", "emotion"],
    content: [
      { type: "paragraph", text: "Difficult conversations are hard because they are two conversations at once. One is about the topic: a boundary, a mistake, a disappointment, a negotiation. The other is about emotional safety: Am I being blamed? Am I respected? Will this relationship survive the truth?" },
      { type: "heading", text: "Calmness keeps the prefrontal system available" },
      { type: "paragraph", text: "When emotion rises, the body prepares to defend. Heart rate increases. Attention narrows. Tone changes. The brain starts optimizing for protection instead of understanding. Calmness is the trained ability to notice that shift without becoming it." },
      { type: "paragraph", text: "This does not mean suppressing emotion. Suppression often leaks through tone. Real calmness means slowing down enough to choose a response. You can be firm and calm. You can be hurt and calm. You can disagree and calm the room at the same time." },
      { type: "quote", text: "Calmness is not the absence of emotion. It is leadership over the next sentence." },
      { type: "heading", text: "The most powerful move is clarification" },
      { type: "paragraph", text: "In tense moments, people often defend too early. A better move is clarification: 'Can you say more about what felt frustrating?' or 'I want to understand the impact before I respond.' Clarification buys time, lowers threat, and keeps reasoning active." },
      { type: "paragraph", text: "Another powerful move is naming intention. 'I am bringing this up because I want us to work better, not because I want to blame you.' The sentence creates emotional context for the hard message." },
      { type: "heading", text: "Practice before the real conversation" },
      { type: "paragraph", text: "The worst time to invent calm language is when you are already activated. Practice gives you options before emotion narrows them. You can rehearse the opening, likely pushback, and the moment where you usually become defensive." },
      { type: "insight", title: "Conversation drill", text: "Practice saying the hard sentence slowly. Then practice responding to the first emotional objection without defending." },
      { type: "paragraph", text: "RehearseAI simulates realistic emotional tension so you can build calmness as a repeatable communication skill, not a personality trait you hope appears on demand." },
    ],
  },
  {
    kind: "blog",
    slug: "practice-public-speaking-without-an-audience",
    title: "How to Practice Public Speaking Without an Audience",
    excerpt: "You do not need a room full of people to train presence, clarity, and Q&A recovery. You need pressure and feedback.",
    category: "Public Speaking",
    author: "RehearseAI Research",
    readTime: "8 min read",
    publishedAt: "2026-05-11",
    heroImage: "public-speaking",
    tags: ["public speaking", "practice", "presentation"],
    content: [
      { type: "paragraph", text: "Public speaking advice often assumes you have access to an audience. Most people do not. They practice alone, maybe record themselves once, then hope the real room will feel manageable. The problem is that public speaking is not only delivery. It is pressure, attention, interruption, and recovery." },
      { type: "heading", text: "Practice the moments that break structure" },
      { type: "paragraph", text: "A presentation usually falls apart in specific places: the opening, the transition from slide to story, the first skeptical question, the moment you lose your place, or the ending. Practicing the whole talk from start to finish is useful, but practicing these fragile moments is more efficient." },
      { type: "paragraph", text: "You can train the opening until your body recognizes it. You can train a difficult question until you stop hearing it as an attack. You can train a recovery phrase: 'Let me reframe that more clearly.' These are small moves with large effects." },
      { type: "quote", text: "Public speaking confidence comes from rehearsed recovery, not perfect memory." },
      { type: "heading", text: "Simulate audience cognition" },
      { type: "paragraph", text: "An audience is not passive. People are confused, skeptical, distracted, supportive, impatient, curious, or unconvinced. Practicing without an audience should still include those mental states. Ask: Where would someone get lost? Where would they doubt the claim? What would they need to believe next?" },
      { type: "paragraph", text: "This turns practice from performance repetition into audience modeling. You learn to guide attention, not just recite content." },
      { type: "heading", text: "Use AI as a pressure audience" },
      { type: "paragraph", text: "AI can simulate the missing room. It can ask skeptical questions, interrupt for clarity, or play a confused listener. The value is not that AI replaces humans. It creates repetitions that would otherwise be unavailable." },
      { type: "insight", title: "Solo speaking drill", text: "Deliver a two-minute version, then answer three skeptical questions without restarting. Recovery matters more than polish." },
      { type: "paragraph", text: "RehearseAI gives speakers a live pressure audience before the real audience appears. You practice the thinking, not just the script." },
    ],
  },
  {
    kind: "blog",
    slug: "why-follow-up-questions-destroy-weak-reasoning",
    title: "Why Follow-Up Questions Destroy Weak Reasoning",
    excerpt: "A first answer can sound polished. Follow-ups reveal whether the reasoning underneath is strong enough to stand.",
    category: "Reasoning",
    author: "RehearseAI Research",
    readTime: "9 min read",
    publishedAt: "2026-05-13",
    heroImage: "follow-up-questions",
    tags: ["reasoning", "interviews", "follow-up"],
    content: [
      { type: "paragraph", text: "Most weak reasoning survives the first question. It dies on the follow-up. The first answer can be prepared, polished, and general enough to sound acceptable. Then someone asks, 'Why?' or 'Can you give an example?' or 'What would you do if that failed?' Suddenly the structure is exposed." },
      { type: "heading", text: "Follow-ups test the load-bearing parts" },
      { type: "paragraph", text: "A strong answer has load-bearing parts: evidence, causality, tradeoffs, assumptions, and implications. A weak answer has surface fluency. It may sound smooth, but it cannot handle pressure because there is no deeper structure to inspect." },
      { type: "paragraph", text: "This is why follow-ups feel aggressive even when they are neutral. They force you to move from statement to reasoning. If the reasoning is unclear, your voice may become defensive, your answer may widen, and your confidence may drop." },
      { type: "quote", text: "A follow-up is not a trap. It is an x-ray of your logic." },
      { type: "heading", text: "The danger of generic claims" },
      { type: "paragraph", text: "Generic claims fail quickly. 'I am a strong leader.' How do you know? 'I care about users.' What tradeoff did that change? 'I can handle ambiguity.' What decision did you make without enough information? The follow-up asks the claim to pay rent." },
      { type: "paragraph", text: "The fix is to attach claims to proof. Instead of saying you are strategic, describe a strategic decision. Instead of saying you communicate well, show a moment where communication changed an outcome." },
      { type: "heading", text: "Practice follow-up chains" },
      { type: "paragraph", text: "A single answer is not enough. Practice chains: answer, follow-up, counterexample, deeper follow-up, interruption, recovery. This reveals where your reasoning becomes thin. It also teaches you to enjoy inspection rather than fear it." },
      { type: "insight", title: "Reasoning drill", text: "For every claim, ask: What evidence supports this? What assumption could be challenged? What tradeoff did I make?" },
      { type: "paragraph", text: "RehearseAI uses follow-ups as a training instrument. It does not reward polished vagueness. It helps you build answers that remain credible after pressure arrives." },
    ],
  },
  {
    kind: "blog",
    slug: "pressure-training-missing-layer-communication-coaching",
    title: "Pressure Training: The Missing Layer in Communication Coaching",
    excerpt: "Most coaching improves what people say in theory. Pressure training improves what they can access in the moment.",
    category: "Pressure Training",
    author: "RehearseAI Research",
    readTime: "10 min read",
    publishedAt: "2026-05-15",
    heroImage: "pressure-training",
    tags: ["coaching", "pressure", "communication"],
    content: [
      { type: "paragraph", text: "Communication coaching often focuses on content: stronger answers, better stories, clearer frameworks, more confident body language. These matter. But they miss the layer that determines whether the skill appears when it counts: pressure." },
      { type: "heading", text: "Knowing the move is not the same as making it live" },
      { type: "paragraph", text: "A person may know they should pause before answering. They may know they should use evidence. They may know they should not become defensive. But when a skeptical person interrupts, the nervous system may choose speed, protection, or over-explanation. The skill disappears because it was never trained under load." },
      { type: "paragraph", text: "Athletes understand this. Musicians understand this. Pilots understand this. Performance changes under pressure, so practice has to include pressure. Communication is no different." },
      { type: "quote", text: "The missing question is not 'What should I say?' It is 'Can I still think when the room changes?'" },
      { type: "heading", text: "Pressure training makes communication measurable" },
      { type: "paragraph", text: "Once pressure is simulated, patterns become visible. Confidence drops after interruption. Clarity falls when the question is abstract. Reasoning improves when the speaker slows down. Persuasion weakens when evidence is missing. These patterns are far more useful than generic feedback like 'be more confident.'" },
      { type: "paragraph", text: "The goal is not to manufacture a fearless personality. It is to build a reliable response system: hear the challenge, stabilize, structure the answer, support the claim, recover if needed." },
      { type: "heading", text: "AI makes pressure repetitions accessible" },
      { type: "paragraph", text: "Most people cannot hire a panel, skeptical interviewer, investor, professor, and conflict partner every day. AI can create those repetitions at low friction. The important thing is that the AI must be structured as a rehearsal system, not a casual chatbot." },
      { type: "insight", title: "Coaching evolution", text: "The future of communication training is not scripts. It is adaptive pressure, reasoning analytics, and longitudinal feedback." },
      { type: "paragraph", text: "RehearseAI exists for that missing layer. It helps people practice the moment before it matters, then understand how their thinking changed inside the pressure." },
    ],
  },
];

export function getBlog(slug: string) {
  return blogs.find((post) => post.slug === slug);
}
